name: ai_text_checker
description: AI Text Checker App with Cyberpunk Theme

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '3.1.5'
  flutter: "3.13.9"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^10.3.3
  image_picker: ^1.0.2
  google_fonts: ^5.1.0
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.2.0
  glass_kit: ^3.0.0
  camera: ^0.10.5+5
  permission_handler: ^10.4.5
  provider: ^6.0.5
  ffi: ^1.2.1
  shared_preferences: ^2.2.2
  google_mlkit_text_recognition: ^0.11.0
  image: ^4.1.3
  path_provider: ^2.1.1
  excel: ^2.1.0
  csv: ^5.1.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: false
  image_path: "assets/app_icon.png"

dependency_overrides:
  google_mlkit_commons: ^0.11.0