name: ai_text_checker
description: AI Text Checker App with Cyberpunk Theme

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=3.13.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^10.3.3
  google_fonts: ^5.1.0
  flutter_animate: ^4.2.0
  camera: ^0.11.2
  permission_handler: ^12.0.1
  provider: ^6.0.5
  ffi: ^2.1.4
  shared_preferences: ^2.5.3
  google_mlkit_text_recognition: ^0.15.0
  image: ^4.3.0
  path_provider: ^2.1.1
  excel: ^2.1.0
  csv: ^5.1.1
  intl: ^0.18.1
  share_plus: ^12.0.0
  cross_file: ^0.3.4
  tflite_flutter: ^0.11.0
  # Removed unused dependencies: image_picker, animated_text_kit, glass_kit,
  # device_info_plus, flutter_image_compress, image_cropper, flutter_isolate,
  # wakelock_plus

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: false
  image_path: "assets/app_icon.png"

# dependency_overrides:
#  google_mlkit_commons: ^0.11.0