import 'settings_manager.dart';

class AppLocalizations {
  static const _en = {
    'system_config': 'SYSTEM CONFIG',
    'neural_network_settings': 'NEURAL NETWORK SETTINGS',
    'detection_settings': 'DETECTION SETTINGS',
    'high_accuracy_mode': 'High Accuracy Mode',
    'auto_scan_documents': 'Auto-scan Documents',
    'detection_sensitivity': 'Detection Sensitivity',
    'system_preferences': 'SYSTEM PREFERENCES',
    'notifications': 'Notifications',
    'data_privacy': 'DATA & PRIVACY',
    'clear_scan_history': 'Clear Scan History',
    'export_data': 'Export Data',
    'file_upload_title': 'NEURAL UPLOAD',
    'upload_placeholder': 'DROP ZONE ACTIVE',
    'quantum_ready': 'QUANTUM READY',
    'analyze': 'ANALYZE',
  'processing': 'PROCESSING...',
    'browse_files': 'BROWSE FILES',
    'neural_editor': 'NEURAL EDITOR',
    'real_time_ai': 'REAL-TIME AI ANALYSIS',
    'analyze_button': 'ANALYZE',
    'recent_scans': 'RECENT SCANS',
    'neural_analysis_complete': 'NEURAL ANALYSIS COMPLETE',
    'ai_detection_label': 'AI Detection: {pct}%',
    'human_written_label': 'Ditulis Manusia: {pct}%',
    'close': 'TUTUP',
    'analysis_complete_notification': 'Analisis selesai',
    'analysis_complete_message': '{what} telah dianalisis',
    'editor_hint': 'Mulai ketik atau tempel teks untuk analisis neural...\n\n• Deteksi AI waktu nyata\n• Pemrosesan kuantum\n• Analisis jaringan neural',
    'initializing_camera': 'Inisialisasi kamera...',
    'camera_permission_required': 'Izin kamera diperlukan',
    'keep': 'Simpan',
    'cancel': 'Batal',
    'kept_image_deleted': 'Gambar yang disimpan dihapus',
    'no_cameras_available': 'Tidak ada kamera pada perangkat ini',
    'please_allow_camera_browser': 'Silakan izinkan akses kamera pada pengaturan browser Anda',
    'error_initializing_camera': 'Gagal inisialisasi kamera. Periksa izin kamera',
    'error_taking_picture': 'Terjadi kesalahan saat mengambil gambar: {err}',
    'flash_not_available': 'Flash tidak tersedia: {err}',
    'capture_label': 'AMBIL',
    'file_pick_failed': 'Failed to pick file: {err}',
    'history_description': 'Complete history of all quantum document analyses',
    'sort_az': 'A - Z',
    'sort_newest': 'Terbaru',
    'sort_oldest': 'Terlama',
    'sort_badge_az': 'A-Z',
    'sort_badge_new': 'BARU',
    'sort_badge_old': 'LAMA',
    'locked_badge': 'TERKUNCI',
    'low_label': 'Rendah',
    'high_label': 'Tinggi',
  };

  static const _id = {
    'system_config': 'SYSTEM CONFIG',
    'neural_network_settings': 'PENGATURAN JARINGAN NEURAL',
    'detection_settings': 'PENGATURAN DETEKSI',
    'high_accuracy_mode': 'Mode Akurasi Tinggi',
    'auto_scan_documents': 'Pindai Dokumen Otomatis',
    'detection_sensitivity': 'Sensitivitas Deteksi',
    'system_preferences': 'PREFERENSI SISTEM',
    'notifications': 'Notifikasi',
    'data_privacy': 'DATA & PRIVASI',
    'clear_scan_history': 'Hapus Riwayat Scan',
    'export_data': 'Ekspor Data',
    'file_upload_title': 'UPLOAD NEURAL',
    'upload_placeholder': 'AREA DROP AKTIF',
    'quantum_ready': 'READY QUANTUM',
    'analyze': 'ANALISIS',
  'processing': 'MEMPROSES...',
    'browse_files': 'TELUSURI FILE',
    'neural_editor': 'EDITOR NEURAL',
    'real_time_ai': 'ANALISIS AI WAKTU NYATA',
    'analyze_button': 'ANALISIS',
    'recent_scans': 'SCAN TERBARU',
    'neural_analysis_complete': 'ANALISIS NEURAL SELESAI',
    'ai_detection_label': 'Deteksi AI: {pct}%',
    'human_written_label': 'Ditulis Manusia: {pct}%',
    'close': 'TUTUP',
    'analysis_complete_notification': 'Analisis selesai',
    'analysis_complete_message': '{what} telah dianalisis',
    'editor_hint': 'Mulai ketik atau tempel teks untuk analisis neural...\n\n• Deteksi AI waktu nyata\n• Pemrosesan kuantum\n• Analisis jaringan neural',
    'initializing_camera': 'Inisialisasi kamera...',
    'camera_permission_required': 'Izin kamera diperlukan',
    'keep': 'Simpan',
    'cancel': 'Batal',
    'kept_image_deleted': 'Gambar yang disimpan dihapus',
    'no_cameras_available': 'Tidak ada kamera pada perangkat ini',
    'please_allow_camera_browser': 'Silakan izinkan akses kamera pada pengaturan browser Anda',
    'error_initializing_camera': 'Gagal inisialisasi kamera. Periksa izin kamera',
    'error_taking_picture': 'Terjadi kesalahan saat mengambil gambar: {err}',
    'flash_not_available': 'Flash tidak tersedia: {err}',
    'capture_label': 'AMBIL',
    'file_pick_failed': 'Gagal memilih file: {err}',
    'history_description': 'Seluruh riwayat semua analisis dokumen kuantum',
    'sort_az': 'A - Z',
    'sort_newest': 'Terbaru',
    'sort_oldest': 'Terlama',
    'sort_badge_az': 'A-Z',
    'sort_badge_new': 'BARU',
    'sort_badge_old': 'LAMA',
    'locked_badge': 'TERKUNCI',
    'low_label': 'Rendah',
    'high_label': 'Tinggi',
  };
  

  static String t(String key) {
    final lang = SettingsManager.currentLanguage;
    if (lang == 'id') return _id[key] ?? key;
    return _en[key] ?? key;
  }
}

