name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master, optimize/android-size ]

defaults:
  run:
    shell: bash -l {0}

permissions:
  contents: read

jobs:
  build-apk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [release, profile]
        target_platform: [android-arm64, android-arm]
    container:
      image: cirrusci/flutter:stable
    env:
      ANDROID_SDK_ROOT: /opt/android/sdk
      JAVA_TOOL_OPTIONS: -Xmx4g
    steps:
      # ... existing steps ...
      
      - name: Build APK with optimized settings
        run: |
          # Clean build to ensure fresh compilation
          flutter clean
          
          # Get dependencies with resolution strategy
          flutter pub get --resolution overridestransient
          
          # Build with optimized settings based on matrix
          flutter build apk --${{ matrix.build_type }} \
            --target-platform ${ matrix.target_platform } \
            --split-per-abi \
            --obfuscate \
            --split-debug-info=build/symbols \
            --tree-shake-icons \
            --no-pub \
            --dart-define=FLUTTER_WEB_CANV_SKIA=true \
            --dart-define=FLUTTER_WEB_USE_SKIA=true \
            --dart-define=FLUTTER_WEB_AUTO_DETECT=true \
            --dart-define=FLUTTER_WEB_CANVASKit_EXPERIMENTAL=true
            
      - name: Analyze APK size and performance
        run: |
          # Install APK Analyzer if not available
          if ! command -v apk-analyzer &> /dev/null; then
            wget -q https://dl.google.com/android/repository/apkanalyzer-8.1.1-linux.zip
            unzip -q apkanalyzer-8.1.1-linux.zip -d apkanalyzer
            chmod +x apkanalyzer/apkanalyzer
            export PATH=$PATH:$PWD/apkanalyzer
          fi
          
          # Analyze APK size
          mkdir -p apk_analysis
          for apk in build/app/outputs/**/*.apk; do
            if [ -f "$apk" ]; then
              apk_name=$(basename "$apk")
              echo "Analyzing $apk_name..."
              apk-analyzer -h text "$apk" > "apk_analysis/${apk_name%.apk}_analysis.txt"
              
              # Extract size breakdown
              echo "Size breakdown for $apk_name:" >> size_report.txt
              grep -A 20 "APK Size" "apk_analysis/${apk_name%.apk}_analysis.txt" >> size_report.txt
            fi
          done
          
          # Generate size comparison report
          python3 scripts/compare_apk_sizes.py apk_analysis/ > size_comparison.txt || true
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifacts-${{ matrix.build_type }}-${{ matrix.target_platform }}
          path: |
            build/app/outputs/**/*.apk
            apk_analysis/**
            size_report.txt
            size_comparison.txt
          if-no-files-found: warn