# Nama Workflow yang akan muncul di GitHub Actions
name: Flutter Build & Optimize

# Trigger: Kapan workflow ini dijalankan?
on:
  # 1. Jalankan otomatis saat ada push ke branch main/master
  push:
    branches: [ main, master ]

  # 2. Jalankan otomatis saat ada Pull Request yang menargetkan main/master
  pull_request:
    branches: [ main, master ]

  # 3. Izinkan untuk dijalankan secara manual dari halaman Actions
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Pilih jenis build yang ingin dijalankan'
        required: true
        default: 'quick_apk'
        type: choice
        options:
          - quick_apk          # Cepat: Hanya build APK dasar untuk testing
          - full_release_aab   # Lengkap: Build AAB & APK ter-optimasi untuk rilis
          - all                # Jalankan semua jenis build
      flutter_channel:
        description: 'Pilih channel Flutter'
        required: true
        default: 'stable'
        type: choice
        options:
          - stable
          - beta
          - master

# Variabel lingkungan global
env:
  JAVA_TOOL_OPTIONS: -Xmx4g # Berikan lebih banyak memori untuk Gradle
  FLUTTER_CHANNEL: ${{ github.event.inputs.flutter_channel || 'stable' }}
  BUILD_TYPE: ${{ github.event.inputs.build_type || 'quick_apk' }}

# Definisi Job
jobs:
  build:
    name: Build & Analyze
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout kode sumber
      # - Menggunakan action resmi, versi dipin (diamankan) untuk kestabilan
      - name: Checkout repository
        uses: actions/checkout@v4 # Pin ke versi spesifik untuk keamanan

      # Langkah 2: Setup Java JDK
      # - Flutter membutuhkan Java. Versi 17 adalah pilihan yang aman dan modern.
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Langkah 3: Setup Android SDK
      # - **GANTI BESAR**: Menggunakan action resmi yang menggantikan semua skrip instalasi SDK yang panjang dan rentan error.
      # - Jauh lebih andal, cepat, dan mudah dikelola.
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3 # Pin ke versi spesifik

      # Langkah 4: Setup Flutter
      # - Menggunakan action resmi untuk setup Flutter dengan caching otomatis.
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      # Langkah 5: Install dependensi Flutter
      - name: Install Flutter dependencies
        run: flutter pub get

      # --- LOGIKA BUILD KONDISIONAL ---
      # Langkah-langkah berikut hanya akan dijalankan berdasarkan input `build_type`

      # Build 1: APK Cepat (untuk testing cepat)
      - name: 🚀 Build Quick APK (arm64)
        if: env.BUILD_TYPE == 'quick_apk' || env.BUILD_TYPE == 'all'
        run: |
          echo "Building quick APK for arm64..."
          flutter build apk --release --target-platform android-arm64

      # Build 2: AAB Rilis Lengkap (untuk publikasi ke Play Store)
      - name: 📦 Build Full Release AAB (with Obfuscation & Size Analysis)
        if: env.BUILD_TYPE == 'full_release_aab' || env.BUILD_TYPE == 'all'
        run: |
          echo "Building optimized AAB for release..."
          flutter build appbundle \
            --release \
            --obfuscate \
            --split-debug-info=build/symbols \
            --analyze-size \
            --tree-shake-icons

      # Build 3: APK Split-per-ABI (untuk distribusi manual)
      - name: 📱 Build Split-per-ABI APKs (with Obfuscation)
        if: env.BUILD_TYPE == 'full_release_aab' || env.BUILD_TYPE == 'all'
        run: |
          echo "Building optimized split-per-ABI APKs..."
          flutter build apk \
            --release \
            --split-per-abi \
            --obfuscate \
            --split-debug-info=build/symbols \
            --tree-shake-icons

      # --- UPLOAD ARTEFAK ---
      # Langkah terakhir: Unggah semua hasil build dan log

      - name: Upload Build Artifacts
        # `if: always()` memastikan langkah ini tetap berjalan meskipun build gagal,
        # sehingga kita bisa mengumpulkan log untuk debugging.
        if: always()
        uses: actions/upload-artifact@v4
        with:
          # Nama artefak menjadi unik untuk setiap run
          name: build-artifacts-${{ env.BUILD_TYPE }}-${{ github.run_number }}
          # Path menggunakan wildcard untuk menangkap semua output yang relevan
          path: |
            build/app/outputs/**/*.apk
            build/app/outputs/**/*.aab
            build/**/app_size_*.json
            build/symbols/**
          # Jika tidak ada file yang ditemukan, jangan gagalkan langkahnya
          if-no-files-found: warn