name: Build Android Split APKs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-split-apks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java (required for Gradle)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Cache pub and gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/.gradle/caches
          key: ${{ runner.os }}-pub-gradle-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-gradle-

      - name: Install dependencies
        run: flutter pub get

      - name: Build arm64-v8a APK (release)
        run: flutter build apk --release --target-platform android-arm64 --split-per-abi -- -PenableMinify=true
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}

      - name: Show outputs
        run: ls -lah build/app/outputs/flutter-apk

      - name: Upload arm64 APK
        uses: actions/upload-artifact@v4
        with:
          name: android-arm64-apk
          path: build/app/outputs/flutter-apk/*arm64_v8a*.apk
